name: Deploy to Salesforce

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          npm install sfdx-cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDXDEV_AUTH_URL }}" > sfdx_auth_url.txt
          sfdx auth:sfdxurl:store -f sfdx_auth_url.txt -a DevHub

      - name: Deploy to Salesforce
        run: |
          sfdx force:source:deploy -p force-app -u DevHub