name: Deploy to Salesforce

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Salesforce CLI with NPM
        run: |
          npm install @salesforce/cli --global

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDXDEV_AUTH_URL }}" |sf org login sfdx-url --alias  Devorg --set-default  --sfdx-url-stdin

      - name: Deploy to Salesforce
        run: |
          sf project deploy start --target-org Devorg --wait 30